export interface PhoneCode {
  country: string;
  code: string;
  dialCode: string;
  flag: string;
}

export const COUNTRIES: string[] = [
  'Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Argentina', 'Armenia',
  'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados',
  'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina',
  'Botswana', 'Brazil', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia',
  'Cameroon', 'Canada', 'Cape Verde', 'Central African Republic', 'Chad', 'Chile', 'China',
  'Colombia', 'Comoros', 'Congo', 'Costa Rica', 'Croatia', 'Cuba', 'Cyprus', 'Czech Republic',
  'Denmark', 'Djibouti', 'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador',
  'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia', 'Fiji', 'Finland',
  'France', 'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Grenada',
  'Guatemala', 'Guinea', 'Guyana', 'Haiti', 'Honduras', 'Hungary', 'Iceland', 'India',
  'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan',
  'Kazakhstan', 'Kenya', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho',
  'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Madagascar', 'Malawi',
  'Malaysia', 'Maldives', 'Mali', 'Malta', 'Mauritania', 'Mauritius', 'Mexico', 'Moldova',
  'Monaco', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia',
  'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North Macedonia',
  'Norway', 'Oman', 'Pakistan', 'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay',
  'Peru', 'Philippines', 'Poland', 'Portugal', 'Qatar', 'Romania', 'Russia', 'Rwanda',
  'Saudi Arabia', 'Senegal', 'Serbia', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia',
  'Somalia', 'South Africa', 'South Korea', 'South Sudan', 'Spain', 'Sri Lanka', 'Sudan',
  'Suriname', 'Sweden', 'Switzerland', 'Syria', 'Taiwan', 'Tajikistan', 'Tanzania',
  'Thailand', 'Togo', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan', 'Uganda',
  'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States', 'Uruguay',
  'Uzbekistan', 'Venezuela', 'Vietnam', 'Yemen', 'Zambia', 'Zimbabwe'
];

export const PHONE_CODES: PhoneCode[] = [
  { country: 'Egypt', code: 'EG', dialCode: '+20', flag: '🇪🇬' },
  { country: 'United States', code: 'US', dialCode: '+1', flag: '🇺🇸' },
  { country: 'United Kingdom', code: 'GB', dialCode: '+44', flag: '🇬🇧' },
  { country: 'United Arab Emirates', code: 'AE', dialCode: '+971', flag: '🇦🇪' },
  { country: 'Saudi Arabia', code: 'SA', dialCode: '+966', flag: '🇸🇦' },
  { country: 'Germany', code: 'DE', dialCode: '+49', flag: '🇩🇪' },
  { country: 'France', code: 'FR', dialCode: '+33', flag: '🇫🇷' },
  { country: 'Italy', code: 'IT', dialCode: '+39', flag: '🇮🇹' },
  { country: 'Spain', code: 'ES', dialCode: '+34', flag: '🇪🇸' },
  { country: 'Netherlands', code: 'NL', dialCode: '+31', flag: '🇳🇱' },
  { country: 'Turkey', code: 'TR', dialCode: '+90', flag: '🇹🇷' },
  { country: 'India', code: 'IN', dialCode: '+91', flag: '🇮🇳' },
  { country: 'China', code: 'CN', dialCode: '+86', flag: '🇨🇳' },
  { country: 'Japan', code: 'JP', dialCode: '+81', flag: '🇯🇵' },
  { country: 'South Korea', code: 'KR', dialCode: '+82', flag: '🇰🇷' },
  { country: 'Brazil', code: 'BR', dialCode: '+55', flag: '🇧🇷' },
  { country: 'Canada', code: 'CA', dialCode: '+1', flag: '🇨🇦' },
  { country: 'Australia', code: 'AU', dialCode: '+61', flag: '🇦🇺' },
  { country: 'Russia', code: 'RU', dialCode: '+7', flag: '🇷🇺' },
  { country: 'Mexico', code: 'MX', dialCode: '+52', flag: '🇲🇽' },
  { country: 'Argentina', code: 'AR', dialCode: '+54', flag: '🇦🇷' },
  { country: 'South Africa', code: 'ZA', dialCode: '+27', flag: '🇿🇦' },
  { country: 'Nigeria', code: 'NG', dialCode: '+234', flag: '🇳🇬' },
  { country: 'Kenya', code: 'KE', dialCode: '+254', flag: '🇰🇪' },
  { country: 'Pakistan', code: 'PK', dialCode: '+92', flag: '🇵🇰' },
  { country: 'Bangladesh', code: 'BD', dialCode: '+880', flag: '🇧🇩' },
  { country: 'Indonesia', code: 'ID', dialCode: '+62', flag: '🇮🇩' },
  { country: 'Malaysia', code: 'MY', dialCode: '+60', flag: '🇲🇾' },
  { country: 'Thailand', code: 'TH', dialCode: '+66', flag: '🇹🇭' },
  { country: 'Vietnam', code: 'VN', dialCode: '+84', flag: '🇻🇳' },
  { country: 'Philippines', code: 'PH', dialCode: '+63', flag: '🇵🇭' },
  { country: 'Singapore', code: 'SG', dialCode: '+65', flag: '🇸🇬' },
  { country: 'Sweden', code: 'SE', dialCode: '+46', flag: '🇸🇪' },
  { country: 'Norway', code: 'NO', dialCode: '+47', flag: '🇳🇴' },
  { country: 'Denmark', code: 'DK', dialCode: '+45', flag: '🇩🇰' },
  { country: 'Finland', code: 'FI', dialCode: '+358', flag: '🇫🇮' },
  { country: 'Switzerland', code: 'CH', dialCode: '+41', flag: '🇨🇭' },
  { country: 'Austria', code: 'AT', dialCode: '+43', flag: '🇦🇹' },
  { country: 'Belgium', code: 'BE', dialCode: '+32', flag: '🇧🇪' },
  { country: 'Poland', code: 'PL', dialCode: '+48', flag: '🇵🇱' },
  { country: 'Portugal', code: 'PT', dialCode: '+351', flag: '🇵🇹' },
  { country: 'Greece', code: 'GR', dialCode: '+30', flag: '🇬🇷' },
  { country: 'Ireland', code: 'IE', dialCode: '+353', flag: '🇮🇪' },
  { country: 'New Zealand', code: 'NZ', dialCode: '+64', flag: '🇳🇿' },
  { country: 'Colombia', code: 'CO', dialCode: '+57', flag: '🇨🇴' },
  { country: 'Chile', code: 'CL', dialCode: '+56', flag: '🇨🇱' },
  { country: 'Peru', code: 'PE', dialCode: '+51', flag: '🇵🇪' },
  { country: 'Morocco', code: 'MA', dialCode: '+212', flag: '🇲🇦' },
  { country: 'Tunisia', code: 'TN', dialCode: '+216', flag: '🇹🇳' },
  { country: 'Algeria', code: 'DZ', dialCode: '+213', flag: '🇩🇿' },
  { country: 'Jordan', code: 'JO', dialCode: '+962', flag: '🇯🇴' },
  { country: 'Lebanon', code: 'LB', dialCode: '+961', flag: '🇱🇧' },
  { country: 'Iraq', code: 'IQ', dialCode: '+964', flag: '🇮🇶' },
  { country: 'Kuwait', code: 'KW', dialCode: '+965', flag: '🇰🇼' },
  { country: 'Qatar', code: 'QA', dialCode: '+974', flag: '🇶🇦' },
  { country: 'Bahrain', code: 'BH', dialCode: '+973', flag: '🇧🇭' },
  { country: 'Oman', code: 'OM', dialCode: '+968', flag: '🇴🇲' },
];
